# Generated by Django 4.0.8 on 2023-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_courses_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.URLField(default='http://google.com', max_length=100),
            preserve_default=False,
        ),
    ]
