# Generated by Django 4.0.8 on 2023-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
