# Generated by Django 4.0.8 on 2023-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_key',
            field=models.CharField(default='id', max_length=50),
        ),
    ]
